# Generated by Django 3.1.4 on 2021-02-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Claims',
            new_name='Claim',
        ),
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.AlterField(
            model_name='track',
            name='image',
            field=models.ImageField(default='images/noimage.jpg', upload_to='{book}/images/'),
        ),
    ]
