# Generated by Django 3.1.6 on 2021-02-21 12:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210216_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
