# Generated by Django 3.1.6 on 2021-02-21 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20210221_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claim',
            old_name='claimant',
            new_name='claimants',
        ),
    ]
