# Generated by Django 3.1.6 on 2021-02-28 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20210221_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='claimants',
        ),
        migrations.AddField(
            model_name='book',
            name='claimants',
            field=models.ManyToManyField(blank=True, default=None, related_name='claimants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='claim',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='initiator', to=settings.AUTH_USER_MODEL),
        ),
    ]
