# Generated by Django 3.1.6 on 2021-02-28 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20210228_1419'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Claim',
        ),
    ]
