# Generated by Django 3.1.6 on 2021-03-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_delete_claim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followers',
        ),
        migrations.AlterField(
            model_name='track',
            name='audio',
            field=models.FileField(upload_to='{book}/audio/'),
        ),
        migrations.AlterField(
            model_name='track',
            name='image',
            field=models.ImageField(blank=True, default='images/noimage.jpg', upload_to='{book}/images/'),
        ),
    ]
